name: CI/CD for Flask App

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6  

    - name: Install dependencies
      run: pip install -r requirements.txt

    # - name: Run tests
    #   run: 


    - name: Build and deploy
      if: success()  # Only deploy if the tests passed
      run: python3 app.py
